export const ACTION_TYPE = {
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_QUESTION_DATA: "SET_QUESTION_DATA",
  SET_QUESTIONS: "SET_QUESTIONS",
  ADD_QUESTION: "ADD_QUESTION",
  SET_QUIZ_RESULTS: "SET_QUIZ_RESULTS",
  SET_SERVER_ERROR: "SET_SERVER_ERROR",
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_QUIZ_LIST: "SET_QUIZ_LIST",
  SET_IS_EDITING: "SET_IS_EDITING",
  SET_QUIZ_ID_TO_EDIT: "SET_QUIZ_ID_TO_EDIT",
  SET_IS_SHOW_QUIZ_PAGE: "SET_IS_SHOW_QUIZ_PAGE",
};
