export const ACTION_TYPE = {
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_QUESTION_DATA: "SET_QUESTION_DATA",
  SET_QUESTIONS: "SET_QUESTIONS",
  ADD_QUESTION: "ADD_QUESTION",
  SET_QUIZ_RESULTS: "SET_QUIZ_RESULTS",
};
